[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

# Enable CORS headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 